### ISSUE TITLE
[GoogleGemini] Google Gemini Adapter

### ISSUE THREAD

**Issue by wachterjohannes** [modelflow-ai/modelflow-ai#108]
- [x] Implement adapter package #107
- [x] Integrate into symfony bundle #109 
- [x] Add to chat project #109
